### ISSUE TITLE
Optware

### ISSUE THREAD

**Issue by mjb9** [dgrant/eyefiserver2#22]
I just upgraded my QNAP & had to reinstall the Eye Fi server (0.0.17). but it appears that Optware isn't in the QNAP App Center anymore. Do you know if there is anyplace to get it, or if there is a substitute?

**Comment by dukesrg** [comment]
It was never available in App Center. Just get qpkg from the download section on github. If you are using QTS 4.0 or older and EyeFi interface is not opening inside QTS, make sure you set WebUI = QTS_desktop in EyeFiServer section of the /etc/config/qpkg.conf (looks like I've messed with the last build)
