### ISSUE TITLE
Eye-Fi Mobi working?

### ISSUE THREAD

**Issue by mawosch** [dgrant/eyefiserver2#9]
Hi,
is the new Eye-Fi Mobi Card working with this tool?
There is no upload-key.

**Comment by m33x** [comment]
Stavros Konstantaras and Connor Dillon from the University of Amsterdam.
https://www.os3.nl/_media/2013-2014/courses/ot/connor_stavros.pdf

I have fixed a minor problem with their code you can find it here: 
https://github.com/michaelbrandt/node-eyefimobiserver/blob/master/related_work/eyefi-mobi.py
